### ISSUE TITLE
add configurable `timeoutMinutes` property to any reusable workflow that is missing it

### ISSUE THREAD

**Issue by jeffsays** [CumulusDS/workflows-public#4]
Some workflows have it, others do not.

[Adding as trackable task inspired by request in slack][slack]

[slack]: https://cumulusds.slack.com/archives/CERA4EYDU/p1737049002832659

Should not be a required property when being called (aka there should be a default value for the parameter in each workflow - whatever the hard value is currently in any workflow where the property is missing)

### example
https://github.com/CumulusDS/workflows-public/blob/c7dac3a35a8fc85b394487f43e576f90009c2e2b/.github/workflows/assign.yml#L1:L17

<details open><summary>workflow with missing parameter</summary>

```yaml
name: Author Assigner
on:
  workflow_call:
    inputs:
      runsOn:
        description: "Runner to use.  Default is 'ubuntu-latest'"
        required: false
        type: string
        default: "ubuntu-latest"
jobs:
  assignAuthor:
    name: Assign author
    runs-on: ${{ inputs.runsOn }}
    timeout-minutes: 5
    steps:
      - name: assign
        uses: technote-space/assign-author@v1
```

</details>

<details open><summary>would become</summary>

```yaml
name: Author Assigner
on:
  workflow_call:
    inputs:
      runsOn:
        description: "Runner to use.  Default is 'ubuntu-latest'"
        required: false
        type: string
        default: "ubuntu-latest"
      timeoutMinutes:
        description: "Timeout in minutes"
        required: false
        type: string
        default: "5"
jobs:
  assignAuthor:
    name: Assign author
    runs-on: ${{ inputs.runsOn }}
    timeout-minutes: ${{ fromJSON(inputs.timeoutMinutes) }}
    steps:
      - name: assign
        uses: technote-space/assign-author@v1
```

</details>

there is a reason why we need to use the fromJSON syntax, but
